name: Publish charts
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/setup-helm@v4.3.0
      with:
         version: 3.17.0
    - name: helm login
      run: echo ${{ secrets.HELM_TOKEN }} | docker login --username github --password-stdin ghcr.io
    - name: helm package
      run: make package
    - name: helm push
      run: make push
