name: Validate charts
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/setup-helm@v4.3.0
      with:
         version: 3.17.0
    - name: lint
      run: make lint
    - name: render
      run: make render
